### PR TITLE
Start Korean translation

### PR DESCRIPTION
**Pull request by sookim-1**
Added Korean as a new language. Translated Welcome ~ Getting Started document first.

### CODE REVIEW

**Comment by mattesmohr** [comment]
Thanks, that you take your time to translate into the Korean language. Is it good for a review? Do you know someone who can take a look at it?

**Comment by sookim-1** [comment]
I don't think there are any Koreans among the contributors.

Can you confirm it with Google Translate?

**Review by 0xTim — CHANGES_REQUESTED** [review]
Thanks for this! I think we can just merge it and fix any issues that come up in the future.

@sookim-1 can you add Korean to https://github.com/vapor/docs/blob/main/.github/workflows/translation-issue-template.md?

**Comment by sookim-1** [comment]
@0xTim  I added Korean to the [translation-issue-template.md file](https://github.com/vapor/docs/blob/main/.github/workflows/translation-issue-template.md).

**Review by 0xTim — APPROVED** [review]
Thanks!

**Pull request merged**
