### PR TITLE
Update models.md to add `Timestampable` section

### PR DESCRIPTION
**Pull request by axtonpitt**
It was difficult to find documentation on how to use `Timestampable`, as it seems similar to Vapor 2 maybe that guide can be used.

(Was not sure which base branch to target as well.)

### CODE REVIEW

**Comment by grundoon** [comment]
Hi @axtonpitt – the `Timestampable` protocol was essentially merged into `Model` for Vapor 3. It no longer exists as a standalone which requires explicit conformance adoption. Rather, it is merely the (optional) presence of the required keys in a model that triggers the functionality, as documented in https://api.vapor.codes/fluent/latest/Fluent/Protocols/Model.html

**Comment by calebkleveter** [comment]
That's true, but I think documenting how to integrate timestamping is a good idea. I think we just need to remove the part about the `Timestampable` protocol.

**Comment by mcdappdev** [comment]
Hi @axtonpitt - let me know if you want to move forward with this. If so, we'll want to address the comments left on this thread, specifically the removal of the `Timestampable` mention. Thanks!

**Comment by axtonpitt** [comment]
Hey @mcdappdev, yeah keen to move forward. Should I keep this PR just to the timestamping properties?

**Comment by mcdappdev** [comment]
Yeah I think that’d be perfect! Thanks again :)

**Comment by axtonpitt** [comment]
Sorry have neglected this PR 😅, #403 looked great and addresses this issue. Closing.

**Pull request closed without merging**
