### PR TITLE
Update the APNS English documentation

### PR DESCRIPTION
**Pull request by Sparklydust**
I have updated the English documentation linked to APNS. 
- The dependency version was not right. 
- The product name was not right. 
- Added import on code example. 
- Remove deprecated `deadline ` parameter for `req.apns.client.sendAlertNotification`.

Update the APNS English documentation

### CODE REVIEW

**Comment by mattesmohr** [comment]
Hey @Sparklydust, I think your PR overlaps with the PR #898. Not sure if the change requests from Tim on the other PR are valid for your PR as well. Also on line 40 there is a typo.

**Comment by Sparklydust** [comment]
@mattesmohr True, I didn't see it. Thank you very much for the insight. I will close this Pull Request then.

**Comment by mattesmohr** [comment]
@Sparklydust Oh sorry, I didn't mean you to close it. Just to revise the changes, Tim has requested. You did a lot more than the PR #898 provides.

**Comment by Sparklydust** [comment]
@mattesmohr No big deal. What would you want me to do? 
- I have checked the changes from #898 and they are the same. 
I didn't need to import  `APNSCore` to make the code compile on my Vapor app like it is discussed [here](https://github.com/vapor/docs/pull/898#discussion_r1325684380).
- I fix the typo but can not reopen the Pull Request as I did a force push with `commit --amend`.

**Comment by Sparklydust** [comment]
@mattesmohr Reopened the Pull Request in case.

**Pull request closed without merging**
