### PR TITLE
Add German translation for authentication.md

### PR DESCRIPTION
**Pull request by mattesmohr**
It adds the German translation for authentication.md. It should be the last translation of the old branch.

### CODE REVIEW

**Comment by 0xTim** [comment]
@mattesmohr is this good to go?

**Comment by mattesmohr** [comment]
> @mattesmohr is this good to go?
> 

Not yet, I want to revise it a bit more.

I guess you can merge the other one. I think Jonas didn't have the time to look at it, but I think it is good to go.

**Comment by 0xTim** [comment]
@mattesmohr cool, want to mark them as draft until they're ready to go? I'll look at the other one

**Comment by mattesmohr** [comment]
> @mattesmohr cool, want to mark them as draft until they're ready to go? I'll look at the other one

Good idea. I will mark it, when I am home from work.

**Comment by Suboptimierer** [comment]
> I think Jonas didn't have the time to look at it, but I think it is good to go.

Sorry for the late reply, @mattesmohr! Unfortunately, I don't have time for that at the moment. But I'm happy to help you with the translations again in 4 weeks ✌🏻

**Comment by mattesmohr** [comment]
> > I think Jonas didn't have the time to look at it, but I think it is good to go.
> 
> 
> 
> Sorry for the late reply, @mattesmohr! Unfortunately, I don't have time for that at the moment. But I'm happy to help you with the translations again in 4 weeks ✌🏻

No pressure. Everything is fine.

**Comment by ptoffy** [comment]
Hey @mattesmohr I'm fluent in German as I'm bilingual, I can review your translations too if @Suboptimierer can't make it! :)

**Comment by mattesmohr** [comment]
Awesome. Good to know! 

I am currently busy with customer projects that I couldn't find the time to translate it further. There are still English parts in it.

But I am eager to finish it as soon I have more time to spare.

**Comment by ptoffy** [comment]
Cool, feel free to ping me or assign me as reviewer when you're done with it

**Comment by mattesmohr** [comment]
I close the PR in favour of #889.

**Pull request closed without merging**
