### PR TITLE
Extend lifecycle handler example

### PR DESCRIPTION
**Pull request by fananek**
Server lifecycle has been extended with `didBoot` and `shutdown` events.

Extend lifecycle handler example.

### CODE REVIEW

**Comment by mattesmohr** [comment]
@fananek Would you mind to add it for the other translations as well? That would be awesome!

**Comment by fananek** [comment]
> @fananek Would you mind to add it for the other translations (Dutch, Chinese) as well? That would be awesome!

I did my best with DeepL support. Hopefully, translations are not that off. :)

**Comment by mattesmohr** [comment]
Oh, I am sorry. Haven't noticed the comments. 😅. I just meant the code. But thank you. I am sure they are correct.

**Review by mattesmohr — APPROVED** [review]
LGTM

**Pull request merged**
