### PR TITLE
# Added Vapor 4.0 Chinese document support.

### PR DESCRIPTION
**Pull request by Jinxiansen**
Hello, the official release of Vapor 4.0 makes me very happy. As a loyal fan who has been using Vapor for more than three years, I decided it was time to contribute to Vapor.
So I spent one night and added support for Vapor 4.0 Chinese documents, hoping to bring a more convenient reading experience for Chinese developers! 💪💪💪

> English is not my native language; please excuse typing errors.

### CODE REVIEW

**Comment by Joannis** [comment]
I can't read chinese, so I can't verify the language of course.
When I click on the chinese language, and then click on an article like "async", I'm back at the english languaged section.

**Comment by Joannis** [comment]
Does anyone know how to localize the menu for this usecase?

**Comment by Jinxiansen** [comment]
@Joannis

Hello there!  The factor I am not sure is that after all the translation is completed, you may have your own concerns or other factors that are not perfect. If you do not agree with the request submitted by me, it is a waste of time to do useless work.
 As for the problem that you can't understand Chinese, I think you can use the Google Chrome plug-in to translate the content of the web page. You can roughly browse it. Although the machine translation is not very accurate, it is similar.
  So, I will translate some first, and then after you agree to merge into the main branch, I will translate later.
  All this is because of my love for Vapor!
  Hope you guys can think about it, thank you very much!

**Comment by 0xTim** [comment]
I think this is a great idea! Just need to see how it works with the current docs site, though I'm sure we can make it work

**Comment by Jinxiansen** [comment]
So, what should I do next?  Can this request be merged?  So that I can confirm that the translation work of subsequent sites and articles can continue.

**Comment by Joannis** [comment]
I think you can continue translating. I do want @tanner0101 's opinion on the file/menu structure. Before merging we need to figure out the organisation of menu items with docs. Although irregardless we can always end up making a new `mkdocs.yml` for chinese with the structure in chinese.

**Comment by stevapple** [comment]
It seems the repo [swiftclub/vapor-docs](https://github.com/swiftclub/vapor-docs) is also working on the Chinese translation of Vapor 4 documents. Does your PR share the same copy with it? @Jinxiansen

**Comment by Jinxiansen** [comment]
@Joannis 

Okay, I will take the time to continue the translation.
In addition, I saw here https://github.com/mkdocs/mkdocs/issues/211#issuecomment-466149476 `tanner0101` tried to find a multi-language support method last year, but there seems to be no friendly solution for the time being.

**Comment by Jinxiansen** [comment]
@stevapple 
Yes, it was a project created by a friend of mine who loves the Vapor framework. I also participated in some of the translations. But if Vapor officially supports Chinese documents, I think this is a greater encouragement for Chinese developers and fans, and it will be easier to use Vapor.

**Comment by stevapple** [comment]
As for Swift itself, Apple encourages independent repos for document translation. I think it’s right because keeping multiple languages in this repo does no good for keeping the translations up to date.

If the final i18n architecture for Vapor documents cannot be determined, it’s a good solution to keep different translations in other repos (forked from this one) and simply add links to them. It’s the simplest way to adopt community i18n works I think. 

And also, vapor can change them into `vapor-community` projects. This would make them much more official 😄

**Comment by 0xTim** [comment]
Where does Swift say to have independent repos for different translations?

I'm happy for this to go into the main repo, as long as we can make the documentation generation work. Even if it has to be on a different domain (like `cn.docs.vapor.codes`)

**Comment by stevapple** [comment]
https://swift.org/documentation/

Here mentions translation works.

**Comment by stevapple** [comment]
I mean vapor can use another repos named like `vapor-community/docs-zh_Hans` or `vapor-community/docs-zh-cn` to keep translated versions, separating documentation and translation works into different domain. 

Also, by following `vapor/docs` as an upstream, translators can easily track the changes in the official (English) document, and have instant updates on their translations.

**Comment by stevapple** [comment]
For deployment, the following commands can quickly add the translated documents:

```bash
git clone https://github.com/<translation repo> <i18n name>
cd <i18n name>
./build.sh
cd ..
```

**Comment by Jinxiansen** [comment]
@Joannis @0xTim 
Hello!
Are tanner0101 very busy these days?
I want to know his opinion on adding multilingual documents and how to configure multiple `mkdocs.yml` files and make them effective.

I did not find an effective solution at https://github.com/mkdocs.

**Comment by tanner0101** [comment]
Thanks for this @Jinxiansen ! You are right that MKDocs doesn't have any built in localization support. I looked into this extensively in the past and I think the best option is to create a separate docs repository using the ISO language code, so in this case `docs-cn`. 

A separate repo will make it easy to deploy these docs to a separate domain, i.e., `cn.docs.vapor.codes`. More importantly though, issues and PRs for these docs will be in Chinese. This means we need separate maintainers that have their own control over the repo. 

This is how Vue.js does it: https://github.com/vuejs/cn.vuejs.org

> Translations for this documentation project are currently maintained in separate repositories forked from this original one.

If this sounds good to everyone, I will create a fork named `docs-cn`. This will need an official maintainer though. @Jinxiansen would you be willing to accept that role?

**Comment by stevapple** [comment]
Maybe `docs.vapor.codes/cn` is a better choice than `cn.docs.vapor.codes`? Using the same domain will make it far easier to add new language support. 

If we use `docs.vapor.codes/cn`, we can simply add a `cn` directory in this repo and use `git submodule` to include `docs-cn`. With an easy modification to `deploy.sh`, the localized version can be easily attached to `docs.vapor.codes` then.

**Comment by tanner0101** [comment]
I'm not sure how we'd get mkdocs to work that way. It needs to be able to make links directly to the GitHub repo for the edit button to work. We also want navigation, site description, etc to be in chinese and we can only have one `mkdocs.yml` file. I'm also not familiar at all with `git submodule` so I'd need to learn more about how that works and any potential issues first. I'd generally be more comfortable following in Vue.js's footsteps here, too. They have extensive docs that cover many different languages and the separate repo / domain system seems to serve them well.

**Comment by stevapple** [comment]
I totally agree with using `docs-cn` for Chinese localization. 

Once it has set up, I’ll try to work out the solution of adding it as a submodule.

**Comment by Jinxiansen** [comment]
@tanner0101 

Thank you very much for your response. Using `cn.docs.vapor.codes` is also a feasible solution. The independent warehouse is easier to maintain. As a big fan of Vapor, I am happy to be able to participate in it and stick to it for a long time.

**Comment by stevapple** [comment]
@tanner0101 @Jinxiansen A very simple `submodule` use case is here. 

https://github.com/stevapple/vapor-docs/tree/submodule

**Comment by OHeroJ** [comment]
hello! Did anyone join the Chinese document translation ?  https://github.com/swiftclub/vapor-docs

**Comment by stevapple** [comment]
@OHeroJ We’re now planning to make an official fork for Chinese localization. You can merge your existing translations by PRs once the Chinese document repo is set up.

**Comment by Jinxiansen** [comment]
@stevapple @OHeroJ 

Perhaps this is also a way, but I think that only translation projects officially supported by Vapor can have a higher degree of recognition and promote everyone's participation, and actively work hard to maintain.

**Comment by stevapple** [comment]
Of course. I just don’t think separate domains are an elegant design. There’re ways to adopt i18n in one site, while keeping them in separate repos.

**Comment by Jinxiansen** [comment]
@stevapple 

大佬，thanks for your suggestion. 🤝
I'm not familiar with i18n; however, I initiated an issue on mkdocs a few days ago, and the suggestion they gave was to add a separate site for each language. Details can be found here: https://github.com/mkdocs/mkdocs/issues/2063

In addition, @tanner0101  may have researched `mkdocs` last year, so in the end he still needs him to make a decision.

**Comment by tanner0101** [comment]
@stevapple ah I see how you made the submodules works. That's interesting, however I'm still not convinced we should go that route for these reasons:

1: I manage the deployment of the docs and I have zero experience with git submodules beyond having looked at what you just shared. What happens if / when things break or get confusing? Doing a quick Google of "git submodules downsides" brings up a lot of results that I don't have the time to digest atm. In a perfect world I could spend time to learn this first and be able to speak more intelligently about the pros and cons.

2: I don't see why `docs.vapor.codes/cn/4.0` is better than `cn.docs.vapor.codes/4.0`? If anything, the domain seems like a more appropriate place for a language code. Ideally we would have a single site with a drop down for selecting language and `Accept-Language` header awareness. That's a direction I'd like to go in the future, but I think for now separate domains is just fine. 

> As a loyal supporter of Vapor, I am very happy to participate and persevere for a long time.

@Jinxiansen great! I'll make the repo now and add you as a maintainer. :)

**Comment by Jinxiansen** [comment]
@tanner0101 
alright, thank you very much!

**Comment by Jinxiansen** [comment]
Thanks tanner !

Chinese site is already supported. 
https://cn.docs.vapor.codes/4.0/

**Pull request closed without merging**
