### PR TITLE
German translation for Contributing Guide

### PR DESCRIPTION
**Pull request by Suboptimierer**
[docs.vapor.codes](docs.vapor.codes) is partially translated to German, but there are still many translations missing. I think it is important that the part explaining how to contribute is translated. Maybe we can motivate more people to translate texts into German by this step ✌🏻

### CODE REVIEW

**Comment by mattesmohr** [comment]
Thats a good idea. Thank you for your help.

I have started the German translation months ago and doing it by hand. Properly it will take some more months to finish it. Still have some translation on my computer and didn't upload it yet, cause I wasn't satisfied enough with it. Need to do.

Would you like to help me on the other translations too?

@0xTim The translation looks good to me.

**Review by 0xTim — APPROVED** [review]
Thanks!

**Comment by Suboptimierer** [comment]
> Would you like to help me on the other translations too?

@mattesmohr Of course, I would be happy to support Vapor in this way 👍🏻

**Comment by mattesmohr** [comment]
Yay! Cool!

I will upload my latest changes in the next couple days and then we can work on #668 together, if you like.  Can I find you Discord?

**Comment by Suboptimierer** [comment]
@mattesmohr Sounds good! I will send you a request on Discord.

**Pull request merged**
