### PR TITLE
Add German translation for logging.md

### PR DESCRIPTION
**Pull request by mattesmohr**
It adds the German translation for logging.md.

### CODE REVIEW

**Comment by 0xTim** [comment]
@mattesmohr is this good to go?

**Comment by mattesmohr** [comment]
Not yet. There is some room for improvement. Some wording I don't like. I will finish it this week and will notify you, when done.

**Comment by 0xTim** [comment]
Cool - no rush just checking!

**Comment by mattesmohr** [comment]
Now, I think it is good to go.

**Review by 0xTim — APPROVED** [review]

**Pull request merged**
