### PR TITLE
Add missing `else` to guard in docs

### PR DESCRIPTION
**Pull request by wSedlacek**
The code as is has a syntax error.

### CODE REVIEW

**Review by MahdiBM — APPROVED** [review]

**Comment by gwynne** [comment]
Nice catch!! Can you also fix the same issue in the translations of that file? It looks like most of them have the same problem.

**Review by gwynne — CHANGES_REQUESTED** [review]
See comment above

**Comment by MahdiBM** [comment]
Yeah i was going to ask about the translations too 😅 https://github.com/vapor/docs/tree/main/docs/basics

**Comment by wSedlacek** [comment]
@gwynne Got the other translations fixed! Good eye!

**Review by 0xTim — APPROVED** [review]
Thanks!

**Pull request merged**
